---
- name: Print Bigpanda payload
  hosts: localhost
  gather_facts: no

  tasks:
    - name: Print the entire payload
      debug:
        var: payloads

    - name: Print entire env variables 
      debug: 
        var: lookup('env')
        
