---
- name: Capture and print payload from stdin
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Create temporary file to store the payload
      tempfile:
        state: file
        suffix: '.json'
      register: tempfile

    - name: Capture payload from stdin and write to temporary file
      shell: 'cat > {{ tempfile.path }}'
      args:
        stdin: yes

    - name: Read and print the payload
      slurp:
        src: "{{ tempfile.path }}"
      register: payload_content

    - name: Print payload
      debug:
        msg: "{{ payload_content.content | b64decode | from_json }}"
