- name: Print bigpanda payload
  hosts: localhost
  gather_facts: yes
  validate_certs: false

  tasks:
        - name: Resolve Incident
          bigpanda.incident.resolve:
            incident_id: "666beda28accb6d17f012410"
            resolution_comment: "Resolved"
            api_token: "BPUAK44abe6c789be95c3552f5dbe78c652e0"
            environment_id: "6578975d1401fd26569fa0f2"
             
      
