---
- name: Print New Relic payload
  hosts: localhost
  gather_facts: no

  tasks:
    - name: Print the entire payload
      debug:
       # var: payload
        msg: |
                  {
            "id": "{{ json_issueId }}",
            "issueUrl": "{{ json_issuePageUrl }}"
          }
