---
- name: Print Bigpanda payload
  hosts: localhost
  gather_facts: no
  vars: 
    payload: "{{incident}}"
  tasks:
    - name: Print the entire payload
      debug:
        var: payload
        

        
